### ISSUE TITLE
SSL cert is not verified

### ISSUE THREAD

**Issue by thoughtless** [exceptional/exceptional#16]
When configure to use SSL, the SSL cert is not verified

```
         client.verify_mode = OpenSSL::SSL::VERIFY_NONE if config.ssl?
```

This eliminates half the benefit of using SSL. Would you mind embedding a CA cert into the gem and setting this to VERIFY_PEER?

Thanks,

**Comment by thoughtless** [comment]
I'm closing this since the project seems to be abandoned.

**Comment by phumpal** [comment]
Hey @thoughtless sorry about that.

We made every attempt to notify existing customers of the exceptional deprecation in favor of Airbrake.

FWIW

| Date         |  Notice |
| ------------- | ------------- |
| 8/26/2014 | First notice to customers the exceptional notifier would be sunset in favor of Airbrake |
| 11/1/2014 | First day exceptional notifiers were proxied to Airbrake |
| 5/18/2016 | First notice of exceptional endpoint shutdown |
| 7/1/2016 | Second notice of exceptional endpoint shutdown |
| 7/26/2016 | Third notice of exceptional shutdown |
| 8/24/2016 | Final reminder of exceptional shutdown |
| 9/1/2016 | Exceptional shutdown | 

I'll submit a PR to mark this repository as deprecated.
